#!/usr/bin/bash

HOME=/data/data/com.termux/files/home
BIN=/data/data/com.termux/files/usr/bin

path="$HOME/Script-II"
cp "$path/fz" "$BIN/fz" >/dev/null 2>&1

help() {
    if [ "$1" == "1" ]; then
        readarray -t invalidArgs < <(for i in "${FLAG_ERR[@]}"; do
            if grep -q "tidak dikenali" <<< "$i"; then
                grep -oP "(?<=\`).*(?=')" <<< "$i"
            else
                cut -b 27 <<< "$i" | xargs -0 -I {} echo -n "-{}"
            fi
        done)
        IFS=","
        echo -e "\e[0;31mArgumen tidak valid\nPassed: ${invalidArgs[*]}\n\e[0m"
    fi
    echo -e "\e[1;32mScript-II by FZ Project\n\e[0m
\e[0;33mPenggunaan: fz [OPSI]\n\e[0m
\e[0;33mPilihan:\e[0m
\e[0;33m-n, --no-root     Jalankan tanpa izin ROOT\e[0m
\e[0;33m-o, --offline     Jalankan tanpa pembaruan skrip\e[0m
\e[0;33m-r, --reinstall   Instal ulang skrip\e[0m
\e[0;33m-h, --help        Mencetak pernyataan bantuan\e[0m

\e[0;32mThank's to: \n[Decipher] https://github.com/decipher3114 \n[Revanced] https://github.com/revanced \n[Revanced Extended] https://github.com/inotia00\e[0m"
    exit "$1"
}

if ! ARGS=$(getopt -o nohr -l "no-root,offline,help,reinstall" -- "$@" 2>/dev/null); then
    readarray -t FLAG_ERR < <(getopt -o nohr -l no-root,offline,help,reinstall -- "$@" 2>&1 1>&-)
    help 1
fi
eval set -- "$ARGS"
while [ $# -gt 0 ]
do
    case "$1" in
    "-h" | "--help")
                        help 0
                        ;;
    "-n" | "--no-root")
                        flag="N"
                        shift
                        ;;
    "-r" | "--reinstall")
                        if ping -c 1 google.com >/dev/null 2>&1; then
                            cd "$path"/.. && rm -rf "$path" && git clone --depth=1 https://github.com/fzscript/Script-II.git && fz && exit
                        else
                            echo -e "\e[0;33mTidak ada koneksi Internet!\e[0m"
                            exit 1
                        fi
                        ;;
    "-o" | "--offline")
                        status="Offline [dipaksa]"
                        shift
                        ;;
    "--")
        shift
        break
        ;;
    esac
    shift
done

if [ "$(getprop ro.product.cpu.abi)" = "armeabi-v7a" ]; then
    echo -e "\e[0;33mArsitektur CPU \"armeabi-v7a\" perangkat Anda tidak didukung untuk mem-patch.\e[0m"
    echo -e "\e[0;33mAnda mungkin mendapatkan kesalahan build.\e[0m"
    read -N 1 -s -r -p $'Tekan ENTER untuk LANJUTKAN atau <SPASI> untuk KELUAR...\n' key
    if [ "$key" = " " ]; then
        echo -e "\e[0;32mKeluar!\e[0m"
        exit
    fi
fi

terminate() {
    clear
    echo -e "\e[0;31mSkrip dihentikan!\e[0m"
    tput cnorm
    exit 1
}
trap terminate SIGTERM SIGINT SIGABRT

DATA="$HOME/FZ/Script-II"
[ ! -d $DATA ] && mkdir -p "$DATA"
# shellcheck source=/dev/null
source "$DATA/.envVars" > /dev/null 2>&1
[ "${lightTheme:-false}" == "true" ] && theme=Light || theme=Dark
export DIALOGRC="$path/configs/.dialogrc$theme"

checkdependencies() {
    if [ -f "$DATA/aapt2" ] && [ -f "$DATA/pup" ] && bins=$(ls "$BIN") && grep -q java <<<"$bins" && grep -q wget <<<"$bins" && grep -q tput <<<"$bins" && grep -q dialog <<<"$bins" && grep -q jq <<<"$bins" && ls "$BIN/fz" >/dev/null 2>&1 && ls "$HOME/storage" >/dev/null 2>&1; then
        return 0
    else
        if ping -c 1 google.com >/dev/null 2>&1; then
            installdependencies || (echo -e "\e[0;31mDependensi tidak diinstal!\e[0m" && exit 1)
        else
            cp "$path/fz" "$BIN/fz"
            echo -e "\e[0;31mDependensi tidak diinstal!\n \e[0;33mJalankan kembali dengan koneksi Internet.\e[0m"
            exit 1
        fi
    fi
}

installdependencies() {
    clear
    echo -e "\e[0;33mMenginstal dependensi...\e[0m"
    arch=$(getprop ro.product.cpu.abi)
    cp "$path/fz" "$BIN/fz"
    sleep 1
    [ ! -d "$HOME/storage" ] && termux-setup-storage
    pkg update -y -o Dpkg::Options::="--force-confnew" || return 1
    pkg install openjdk-17 wget ncurses-utils dialog jq -y -o Dpkg::Options::="--force-confnew" || return 1
    git config --global pull.rebase true
    sed -i '/allow-external-apps/s/# //' "$HOME/.termux/termux.properties"
    [ ! -f "$DATA/aapt2" ] && wget "https://github.com/decipher3114/termux-aapt/releases/download/v0.1/aapt2_$arch" -O "$DATA/aapt2" && chmod +x "$DATA/aapt2"
    [ ! -f "$DATA/pup" ] && wget "https://github.com/decipher3114/pup/releases/download/v0.1/pup_$arch" -O "$DATA/pup" && chmod +x "$DATA/pup"
    echo -e "\e[0;32mDependensi berhasil diinstal.\e[0m"
    return 0
}

checkscripts() {
    if [ -d "$path" ]; then
        cd "$path" >/dev/null 2>&1 || true
        rm -rf ./*cache*
        return 0
    else
        echo -e "\e[0;31mSkrip tidak ditemukan!\e[0m"
        echo -e "\e[0;33mApakah Anda ingin menginstal ulang?\e[0m"
        read -r -p "[Y/N]: " choice
        case "$choice" in
        y | Y)
            rm -rf "$path"
            git clone --depth=1 https://github.com/fzscript/Script-II.git && fz && exit
            ;;
        n | N)
            echo -e "\e[0;33mMenghapus skrip sepenuhnya!\e[0m"
            sleep 0.5s
            rm "$BIN/fz"
            echo -e "\e[0;32mSkrip berhasil dihapus.\e[0m"
            exit 0
            ;;
        ?)
            echo -e "\e[0;31mOpsi tidak valid\e[0m"
            exit 1
            ;;
        esac
    fi
}

checkdependencies
checkscripts
tput civis
dialog --keep-window --no-shadow --keep-window --infobox "\n    █▀ █▀▀ █▀█ █ █▀█ ▀█▀ ▄▄ █ █
\n    ▄█ █▄▄ █▀▄ █ █▀▀ ░█░ ░░ █ █\n\nDiperbarui: Memeriksa...\nStatus    : Memeriksa..." 10 40

if ping -c 1 google.com >/dev/null 2>&1; then
    status=${status:-Online}
else
    status=Offline
fi
if [ "$status" == "Online" ]; then
    git pull >/dev/null 2>&1 || (git fetch --all >/dev/null 2>&1 && git reset --hard "@{u}" >/dev/null 2>&1)
    dialog --no-shadow --infobox "\n    █▀ █▀▀ █▀█ █ █▀█ ▀█▀ ▄▄ █ █
\n    ▄█ █▄▄ █▀▄ █ █▀▀ ░█░ ░░ █ █\n\nDiperbarui: $(git log -1 --pretty='format:%cd' --date=format:'%d-%m-%Y | %H:%M UTC+7')\nStatus    : $status" 10 40
else
    dialog --no-shadow --infobox "\n    █▀ █▀▀ █▀█ █ █▀█ ▀█▀ ▄▄ █ █
\n    ▄█ █▄▄ █▀▄ █ █▀▀ ░█░ ░░ █ █\n\nDiperbarui: $(git log -1 --pretty='format:%cd' --date=format:'%d-%m-%Y | %H:%M UTC+7')\nStatus    : $status" 10 40
fi
cd "$DATA" >/dev/null 2>&1 || true
bash "$path/main.sh" "$flag"
exitstatus=$?
clear
cd "$HOME" || :
if [ $exitstatus -eq 0 ]; then
    echo -e "\e[0;32mKeluar!\e[0m"
else
    echo -e "\e[0;31mSkrip dihentikan!\e[0m"
    rm -rf -- *cache >/dev/null 2>&1
fi
tput cnorm
