#!/usr/bin/bash

HOME=/data/data/com.termux/files/home
BIN=/data/data/com.termux/files/usr/bin

path="$HOME/Patcher"
cp "$path/patcher" "$BIN/patcher" >/dev/null 2>&1

help() {
    if [ "$1" == "1" ]; then
        readarray -t invalidArgs < <(for i in "${FLAG_ERR[@]}"; do
            if grep -q "tidak dikenali" <<< "$i"; then
                grep -oP "(?<=\`).*(?=')" <<< "$i"
            else
                cut -b 27 <<< "$i" | xargs -0 -I {} echo -n "-{}"
            fi
        done)
        IFS=","
        echo -e "\e[1;31mArgumen tidak valid\nPassed: ${invalidArgs[*]}\n\e[0m"
    fi
    echo -e "\e[1;34mPatcher by FZ Project's\n\e[0m
\e[1;33mPenggunaan:\e[0m \e[1;32mpatcher [OPSI]\n\e[0m
\e[1;33mPilihan:\e[0m
\e[1;33m-n, --no-root     \e[1;34mJalankan tanpa izin ROOT\e[0m
\e[1;33m-o, --offline     \e[1;34mJalankan tanpa pembaruan Patcher\e[0m
\e[1;33m-r, --reinstall   \e[1;34mInstal ulang Patcher\e[0m
\e[1;33m-h, --help        \e[1;34mCetak pernyataan Bantuan\e[0m

\e[1;35mRepo GitHub: https://github.com/fzproject/Patcher\nChannel Telegram: https://t.me/fzproject\nGrup Telegram: https://t.me/fzprojectChat\e[0m"
    exit "$1"
}

if ! ARGS=$(getopt -o nohr -l "no-root,offline,help,reinstall" -- "$@" 2>/dev/null); then
    readarray -t FLAG_ERR < <(getopt -o nohr -l no-root,offline,help,reinstall -- "$@" 2>&1 1>&-)
    help 1
fi
eval set -- "$ARGS"
while [ $# -gt 0 ]
do
    case "$1" in
    "-h" | "--help")
                        help 0
                        ;;
    "-n" | "--no-root")
                        flag="N"
                        shift
                        ;;
    "-r" | "--reinstall")
                        if ping -c 1 google.com >/dev/null 2>&1; then
                            cd "$path"/.. && rm -rf "$path" && git clone --depth=1 https://github.com/fzscript/Patcher.git && patcher && exit
                        else
                            echo "Tidak ada koneksi Internet!"
                            exit 1
                        fi
                        ;;
    "-o" | "--offline")
                        status="Offline [dipaksa]"
                        shift
                        ;;
    "--")
        shift
        break
        ;;
    esac
    shift
done

if [ "$(getprop ro.product.cpu.abi)" = "armeabi-v7a" ]; then
    echo "Arsitektur CPU \"armeabi-v7a\" perangkat Anda tidak didukung untuk mem-patch."
    echo "Anda mungkin mendapatkan kesalahan build."
    read -N 1 -s -r -p $'Tekan ENTER untuk LANJUTKAN atau <SPASI> untuk KELUAR...\n' key
    if [ "$key" = " " ]; then
        echo "Keluar!"
        exit
    fi
fi

terminate() {
    clear
    echo "Ditutup paksa."
    tput cnorm
    exit 1
}
trap terminate SIGTERM SIGINT SIGABRT

DATA="$HOME/patcher-data"
[ ! -d $DATA ] && mkdir -p "$DATA"
# shellcheck source=/dev/null
source "$DATA/.envVars" > /dev/null 2>&1
[ "${lightTheme:-false}" == "true" ] && theme=Light || theme=Dark
export DIALOGRC="$path/configs/.dialogrc$theme"

checkdependencies() {
    if [ -f "$DATA/aapt2" ] && [ -f "$DATA/pup" ] && bins=$(ls "$BIN") && grep -q java <<<"$bins" && grep -q wget <<<"$bins" && grep -q tput <<<"$bins" && grep -q dialog <<<"$bins" && grep -q jq <<<"$bins" && ls "$BIN/patcher" >/dev/null 2>&1 && ls "$HOME/storage" >/dev/null 2>&1; then
        return 0
    else
        if ping -c 1 google.com >/dev/null 2>&1; then
            installdependencies || (echo "Dependensi tidak diinstal!" && exit 1)
        else
            cp "$path/patcher" "$BIN/patcher"
            echo -e "Dependensi tidak diinstal!\nJalankan kembali dengan koneksi Internet."
            exit 1
        fi
    fi
}

installdependencies() {
    clear
    echo "Menginstal dependensi..."
    arch=$(getprop ro.product.cpu.abi)
    cp "$path/patcher" "$BIN/patcher"
    sleep 1
    [ ! -d "$HOME/storage" ] && termux-setup-storage
    pkg update -y -o Dpkg::Options::="--force-confnew" || return 1
    pkg install openjdk-17 wget ncurses-utils dialog jq -y -o Dpkg::Options::="--force-confnew" || return 1
    git config --global pull.rebase true
    sed -i '/allow-external-apps/s/# //' "$HOME/.termux/termux.properties"
    [ ! -f "$DATA/aapt2" ] && wget "https://github.com/decipher3114/termux-aapt/releases/download/v0.1/aapt2_$arch" -O "$DATA/aapt2" && chmod +x "$DATA/aapt2"
    [ ! -f "$DATA/pup" ] && wget "https://github.com/decipher3114/pup/releases/download/v0.1/pup_$arch" -O "$DATA/pup" && chmod +x "$DATA/pup"
    echo "Dependensi berhasil diinstal."
    return 0
}

checkproject() {
    if [ -d "$path" ]; then
        cd "$path" >/dev/null 2>&1 || true
        rm -rf ./*cache*
        return 0
    else
        echo -e "\e[1;31mPatcher tidak ditemukan!\e[0m"
        echo -e "\e[1;31mApakah Anda ingin menginstal ulang Patcher?\e[0m"
        read -r -p "[Y/N]: " choice
        case "$choice" in
        y | Y)
            rm -rf "$path"
            git clone --depth=1 https://github.com/fzscript/Patcher.git && patcher && exit
            ;;
        n | N)
            echo "Menghapus patcher sepenuhnya!"
            sleep 0.5s
            rm "$BIN/patcher"
            echo "Patcher berhasil dihapus."
            exit 0
            ;;
        ?)
            echo "Opsi tidak valid"
            exit 1
            ;;
        esac
    fi
}

checkdependencies
checkproject
tput civis
dialog --keep-window --no-shadow --keep-window --infobox "\n      █▀█ ▄▀█ ▀█▀ █▀▀ █░█ █▀▀ █▀█\n      █▀▀ █▀█ ░█░ █▄▄ █▀█ ██▄ █▀▄\n\n  Developer : FZ Project's\n  Diperbarui: Memeriksa...\n  Status    : Memeriksa..." 10 43

if ping -c 1 google.com >/dev/null 2>&1; then
    status=${status:-Online}
else
    status=Offline
fi
if [ "$status" == "Online" ]; then
    git pull >/dev/null 2>&1 || (git fetch --all >/dev/null 2>&1 && git reset --hard "@{u}" >/dev/null 2>&1)
    dialog --no-shadow --infobox "\n      █▀█ ▄▀█ ▀█▀ █▀▀ █░█ █▀▀ █▀█\n      █▀▀ █▀█ ░█░ █▄▄ █▀█ ██▄ █▀▄\n\n  Developer : FZ Project's\n  Diperbarui: $(git log -1 --pretty='format:%cd' --date=format:'%d-%m-%Y | %H:%M UTC+7')\n  Status    : $status" 10 43
else
    dialog --no-shadow --infobox "\n      █▀█ ▄▀█ ▀█▀ █▀▀ █░█ █▀▀ █▀█\n      █▀▀ █▀█ ░█░ █▄▄ █▀█ ██▄ █▀▄\n\n  Developer : FZ Project's\n  Diperbarui: $(git log -1 --pretty='format:%cd' --date=format:'%d-%m-%Y | %H:%M UTC+7')\n  Status    : $status" 10 43
fi
cd "$DATA" >/dev/null 2>&1 || true
bash "$path/main.sh" "$flag"
exitstatus=$?
clear
cd "$HOME" || :
if [ $exitstatus -eq 0 ]; then
    echo "Keluar!"
else
    echo "Ditutup paksa."
    rm -rf -- *cache >/dev/null 2>&1
fi
tput cnorm
